### ISSUE TITLE
Disconnect online control on session reset

### ISSUE THREAD

**Issue by coldfix** [hibtc/madgui-old#95]

**Comment by coldfix** [comment]
Now unnecessary (I think) due to plugin being able to handle multiple segments.

**Comment by coldfix** [comment]
Note that there is an exception, when disconnecting the online control after resetting the session:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 880, in emit
    stream.write(fs % msg)
  File "/home/thomas/src/work/bundle/madgui/madgui/widget/notebook.py", line 540, in write
    wx.CallAfter(self._ctrl.WriteText, text)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16707, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
PyDeadObjectError: The C++ part of the TextCtrl object has been deleted, attribute access no longer allowed.
Logged from file stub.py, line 42
```

This is probably due to the online control trying to log

```
13:49:57 INFO hit.online_control.stub: FreeInterfaceInstance(c_int(0),)
```
